package com.example.lab2

data class Characteristics(
    val age_of_sexual_maturity: String,
    val age_of_weaning: String,
    val average_litter_size: String,
    val biggest_threat: String,
    val color: String,
    val common_name: String,
    val diet: String,
    val estimated_population_size: String,
    val favorite_food: String,
    val gestation_period: String,
    val group: String,
    val group_behavior: String,
    val habitat: String,
    val height: String,
    val length: String,
    val lifespan: String,
    val lifestyle: String,
    val litter_size: String,
    val location: String,
    val main_prey: String,
    val most_distinctive_feature: String,
    val name_of_young: String,
    val number_of_species: String,
    val origin: String,
    val other_names: String,
    val predators: String,
    val skin_type: String,
    val slogan: String,
    val temperament: String,
    val top_speed: String,
    val type: String,
    val weight: String
)
